# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dfb1e8ad7f2f2abba32d87a65172ea205b7cfff5adcc3600338d965b77906b56474bf626f9a458c1f47fadb24adb24a071f2b05335b2f34d55248532fff0cab7

test:
  secret_key_base: bccaa16426d16f9e80d82ee5e86333004ef3f2c6d9aeeebde9ca636e484cee8fa4e1560dbd93c9c57e957750ef0f003e0126a1e96fe19b1aa6b77c3e5542fde8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
